export const codingQuotes = [
  "Talk is cheap. Show me the code. – Linus Torvalds",
  "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
  "First, solve the problem. Then, write the code. – John Johnson",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "Before software can be reusable it first has to be usable. – Ralph Johnson",
  "Make it work, make it right, make it fast. – Kent Beck",
  "Give a man a program, frustrate him for a day. Teach a man to program, frustrate him for a lifetime. – Muhammad Waseem",
  "If debugging is the process of removing bugs, then programming must be the process of putting them in. – Edsger Dijkstra",
  "The most important property of a program is whether it accomplishes the intention of its user. – C.A.R. Hoare",
  "The best way to predict the future is to implement it. – David Heinemeier Hansson",
  "The purpose of software engineering is to control complexity, not to create it. – Pamela Zave",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
  "The key to performance is elegance, not battalions of special cases. – Jon Bentley",
  "Controlling complexity is the essence of computer programming. – Brian Kernighan",
  "Simplicity is the soul of efficiency. – Austin Freeman",
  "There are two ways of constructing a software design: One way is to make it so simple that there are obviously no deficiencies, and the other way is to make it so complicated that there are no obvious deficiencies. The first method is far more difficult. -C.A.R. Hoare",
  "Good code is its own best documentation. – Steve McConnell",
  "Code never lies, comments sometimes do. – Ron Jeffries",
  "It’s not a bug – it’s an undocumented feature. – Anonymous",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "The most disastrous thing that you can ever learn is your first programming language. – Alan Kay",
  "In theory, there is no difference between theory and practice. But, in practice, there is. – Jan L.A. van de Snepscheut",
  "The hardest part of design is keeping features out. – Donald Norman",
  "If you’re not embarrassed by the first version of your product, you’ve launched too late. – Reid Hoffman",
  "Programs are meant to be read by humans and only incidentally for computers to execute. – Harold Abelson",
  "The code you write makes the world. – Jesse James Garrett",
  "It’s not about the code, it’s about the problem it solves. – Anonymous",
  "There are only two hard things in computer science: cache invalidation and naming things. – Phil Karlton",
  "Make it work, make it right, make it fast. – Kent Beck",
  "A good programmer is someone who always looks both ways before crossing a one-way street. – Doug Linder",
  "Software is like sex: It’s better when it’s free. – Linus Torvalds",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "Don’t write better errors, write code that doesn’t need to fail. – Anonymous",
  "Code should be written for humans first, computers second. – Jeff Atwood",
  "It’s not the tools you have faith in. Tools are just tools. They work, or they don’t work. – Larry Wall",
  "Complexity is the enemy of performance. – Tony Hoare",
  "In programming, simplicity and clarity are the highest priorities. – John Carmack",
  "Code is poetry. – WordPress",
  "Good software, like wine, takes time to mature. – Anonymous",
  "The best way to get a good idea is to get a lot of ideas. – Linus Pauling",
  "Programming is thinking, not typing. – Rich Hickey",
  "An optimist is a programmer who writes the code first, then documents it. – Anonymous",
  "The function of good software is to make the complex appear to be simple. – Grady Booch",
  "The most powerful tool we have as programmers is our ability to learn. – Joel Spolsky",
  "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
  "Sometimes the most elegant code is the simplest. – Jon Bentley",
  "The best performance improvement is the transition from the nonworking state to the working state. – John Ousterhout",
  "There are only two hard things in computer science: cache invalidation and naming things. – Phil Karlton",
  "It’s not about being the best, it’s about being better than you were yesterday. – Anonymous",
  "Good programmers know what to write. Great ones know what to rewrite and reuse. – Eric S. Raymond",
  "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
  "Good code is its own best documentation. – Steve McConnell",
  "Programming is one of the most difficult things humans do. – Anonymous",
  "The most complicated skill is to be simple. – Dejan Stojanovic",
  "A person who has never made a mistake has never tried anything new. – Albert Einstein",
  "There are only two hard things in computer science: naming things, cache invalidation, and off-by-one errors. – Jeff Atwood",
  "A great programmer is a rare breed. – Anonymous",
  "We can’t solve problems by using the same kind of thinking we used when we created them. – Albert Einstein",
  "There’s no place like 127.0.0.1. – Anonymous",
  "If you think your code is perfect, then you have not looked hard enough. – Anonymous",
  "The computer is a great tool, but it will never replace a good programmer. – Anonymous",
  "Programmers are constantly on a quest to make things simpler. – Eric S. Raymond",
  "Simplicity is the key to achieving elegance in programming. – Anonymous",
  "The purpose of software engineering is to control complexity, not to create it. – Pamela Zave",
  "To iterate is human, to recurse divine. – L. Peter Deutsch",
  "It’s not a bug – it’s an undocumented feature. – Anonymous",
  "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
  "Code like a poet; think like a philosopher. – Anonymous",
  "Good programmers write good code. Great programmers write code that others can read. – Anonymous",
  "A programmer is just a tool, writing programs for another tool, the computer. – Anonymous",
  "The code that works for the task at hand is the best code. – Anonymous",
  "There is no shortcut to success in coding. – Anonymous",
  "If you fail to plan, you plan to fail in coding. – Anonymous",
  "Your code is your fingerprint. – Anonymous",
  "If you can’t explain it simply, you don’t understand it well enough. – Albert Einstein",
  "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away. – Antoine de Saint-Exupéry",
  "One person’s ‘magic’ is another person’s engineering. – Robert A. Heinlein",
  "Computer programming is an art, like music or painting. – Anonymous",
  "The best way to learn is by doing. – Anonymous",
  "Sometimes the best code is the one that you don’t write. – Anonymous",
  "Learning to code is learning to learn. – Anonymous",
  "Good design adds value faster than it adds cost. – Thomas C. Gale",
  "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
  "There is no bug too big that it can’t be solved with the right mindset. – Anonymous",
  "Simplicity is the soul of efficiency. – Austin Freeman",
  "Code is the new literacy. – Anonymous",
  "You will learn more from your mistakes than your successes. – Anonymous",
  "A programmer is someone who fixes problems that you didn’t know you had. – Anonymous",
  "I’m not a great programmer; I’m just a good one with great habits. – Anonymous",
  "The best kind of programmer is a lazy one. – Anonymous",
  "The best code is no code at all. – Jeff Atwood",
  "The important thing is not to stop questioning. – Albert Einstein",
  "Programming: The art of writing a piece of software that you don’t need, for a problem you don’t have. – Anonymous",
  "To code or not to code, that is not the question. – Anonymous",
  "The code is weak, but the developer is strong. – Anonymous",
  "I am not a great programmer, I’m just a good one with great habits. – Anonymous",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
  "Life is too short for bad code. – Anonymous",
  "Debuggers don't remove bugs. They only show them in slow motion. -Anonymous",
  "Weeks of coding can save you hours of planning -Anonymous",
  "C++: an octopus made by nailing extra legs onto a dog. -Steve Taylor",
  "Nobody should start to undertake a large project. You start with a small trivial project, and you should never expect it to get large. If you do, you'll just overdesign and generally think it is more important than it likely is at that stage. Or worse, you might be scared away by the sheer size of the work you envision. So start small, and think about the details. Don't think about some big picture and fancy design. If it doesn't solve some fairly immediate need, it's almost certainly over-designed. And don't expect people to jump in and help you. That's not how these things work. You need to get something half-way useful first, and then others will say 'hey, that almost works for me,' and they'll get involved in the project. – Linus Torvalds",
  "Better train people and risk they leave – than do nothing and risk they stay. – Anonymous",
  "Before software should be reusable, it should be usable. – Ralph Johnson",
  "The generation of random numbers is too important to be left to chance. – Robert R. Coveyou",
  "Anyone who considers arithmetic methods of producing random digits is, of course, in a state of sin. – John von Neumann (1951)",
  "I love deadlines. I like the whooshing sound they make as they fly by. – Douglas Adams",
  "A good programmer looks both ways before crossing a one-way street.",
  "C: You shoot yourself in the foot.",
  "C++: You accidentally create a dozen instances of yourself and shoot them all in the foot. Providing emergency medical assistance is impossible since you can't tell which are bitwise copies and which are just pointing at others and saying 'That's me, over there.'",
  "FORTRAN: You shoot yourself in each toe, iteratively, until you run out of toes, then you read in the next foot and repeat. If you run out of bullets, you continue anyway because you have no exception-handling facility.",
  "Modula-2: After realizing that you can't actually accomplish anything in this language, you shoot yourself in the head.",
  "COBOL: USEing a COLT 45 HANDGUN, AIM gun at LEG.FOOT, THEN place ARM.HAND.FINGER on HANDGUN.TRIGGER and SQUEEZE. THEN return HANDGUN to HOLSTER. CHECK whether shoelace needs to be retied.",
  "Lisp: You shoot yourself in the appendage which holds the gun with which you shoot yourself in the appendage which holds the gun with which you shoot yourself in the appendage which holds...",
  "BASIC: Shoot yourself in the foot with a water pistol. On big systems, continue until entire lower body is waterlogged.",
  "Forth: Foot yourself in the shoot.",
  "APL: You shoot yourself in the foot; then spend all day figuring out how to do it in fewer characters.",
  "Pascal: The compiler won't let you shoot yourself in the foot.",
  "Snobol: If you succeed, shoot yourself in the left foot. If you fail, shoot yourself in the right foot.",
  "HyperTalk: Put the first bullet of the gun into foot left of leg of you. Answer the result.",
  "Prolog: You tell your program you want to be shot in the foot. The program figures out how to do it, but the syntax doesn't allow it to explain.",
  "370 JCL: You send your foot down to MIS with a 4000-page document explaining how you want it to be shot. Three years later, your foot comes back deep-fried.",
  "FORTRAN-77: You shoot yourself in each toe, iteratively, until you run out of toes, then you read in the next foot and repeat. If you run out of bullets, you continue anyway because you still can't do exception-processing.",
  "Modula-2 (alternative): You perform a shooting on what might be currently a foot with what might be currently a bullet shot by what might currently be a gun.",
  "BASIC (compiled): You shoot yourself in the foot with a BB using a SCUD missile launcher.",
  "Visual Basic: You'll really only appear to have shot yourself in the foot, but you'll have so much fun doing it that you won't care.",
  "Forth (alternative): BULLET DUP3 * GUN LOAD FOOT AIM TRIGGER PULL BANG! EMIT DEAD IF DROP ROT THEN. This takes about five bytes of memory, executes in two to ten clock cycles on any processor, and can be used to replace any existing function of the language as well as in any future words.",
  "APL (alternative): You hear a gunshot and there's a hole in your foot, but you don't remember enough linear algebra to understand what happened.",
  "Pascal (alternative): Same as Modula-2 except that the bullet is not the right type for the gun, and your hand is blown off.",
  "Snobol (alternative): You grab your foot with your hand, then rewrite your hand to be a bullet. The act of shooting the original foot then changes your hand/bullet into yet another foot (a left foot).",
  "Prolog (alternative): You attempt to shoot yourself in the foot, but the bullet, failing to find its mark, backtracks to the gun, which then explodes in your face.",
  "COMAL: You attempt to shoot yourself in the foot with a water pistol, but the bore is clogged, and the pressure build-up blows apart both the pistol and your hand.",
  "Scheme: As Lisp, but none of the other appendages are aware of this happening.",
  "Algol: You shoot yourself in the foot with a musket. The musket is aesthetically fascinating, and the wound baffles the adolescent medic in the emergency room.",
  "Ada: If you are dumb enough to actually use this language, the United States Department of Defense will kidnap you, stand you up in front of a firing squad, and tell the soldiers, 'Shoot at the feet.'",
  "Eiffel: You create a GUN object, two FOOT objects, and a BULLET object. The GUN passes both the FOOT objects a reference to the BULLET. The FOOT objects increment their hole counts and forget about the BULLET. A little demon then drives a garbage truck over your feet and grabs the bullet (both of it) on the way.",
  "Smalltalk: You send the message shoot to gun, with selectors bullet and myFoot. A window pops up saying Gunpowder doesNotUnderstand: spark.",
  "Java: You locate the Gun class, but discover that the Bullet class is abstract, so you extend it and write the missing part of the implementation. Then you implement the ShootAble interface for your foot, and recompile the Foot class. The interface lets the bullet call the doDamage method on the Foot, so the Foot can damage itself in the most effective way.",
  "Artificial Intelligence is no match for natural stupidity. - Unknown",
  "Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the Universe trying to produce bigger and better idiots. So far, the Universe is winning. - Rich Cook",
  "The use of COBOL cripples the mind; its teaching should, therefore, be regarded as a criminal offence. - Edsger Dijkstra",
  "APL is a mistake, carried through to perfection. It is the language of the future for the programming techniques of the past: it creates a new generation of coding bums. - Edsger Dijkstra",
  "If you give someone a program, you will frustrate them for a day; if you teach them how to program, you will frustrate them for a lifetime. - Unknown",
  "WOMBAT: Works On My Box All the Time. - Many developers",
  "The best things are simple, but finding these simple things is not simple. - Unknown",
  "There's no such thing as temporary code. - Unknown",
  "When I am working on a problem I never think about beauty. I think only how to solve the problem. But when I have finished, if the solution is not beautiful, I know it is wrong. - R. Buckminster Fuller",
  "Software is either testable or detestable. - Unknown",
  "The definition of insanity is doing the same thing over and over and expecting a different result. - Misattributed to Ben Franklin or Albert Einstein",
  "If builders built buildings the way programmers write programs, then the first woodpecker that came along would destroy civilization. - Weinberg's Second Law",
  "Are you quite sure that all those bells and whistles, all those wonderful facilities of your so-called powerful programming languages, belong to the solution set rather than the problem set? - Edsger W. Dijkstra",
  "Plans are useless, but planning is indispensable. - Dwight D. Eisenhower",
  "I will claim that the difference between a bad programmer and a good one is whether they consider their code or their data structures more important. Bad programmers worry about the code. Good programmers worry about data structures and their relationships. - Linus Torvalds",
  "Friend: The problem with this code is it has far too many levels of misdirection. Me: Don't you mean indirection? Friend: I meant what I said. - Anonymous",
  "If the automobile had followed the same development cycle as the computer, a Rolls-Royce would today cost $100, get a million miles per gallon, and explode once a year, killing everyone inside. - Robert X. Cringely",
  "In a world without walls and fences, who needs Windows and Gates? - Anonymous",
  "Fixing Unix is easier than living with NT. - Jonathan Gilpin",
  "No code is faster than no code. - Merb motto",
  "WTF?! - Attributed to anybody reading someone else's code",
  "If you lie to the compiler, it will get its revenge. - Henry Spencer",
  "The primary duty of an exception handler is to get the error out of the lap of the programmer and into the surprised face of the user. - Verity Stob",
  "Good code is its own best documentation. As you're about to add a comment, ask yourself, 'How can I improve the code so that this comment isn't needed?' - Steve McConnell",
  "UNIX is simple. But It just needs a genius to understand its simplicity. - Dennis Ritchie",
  "The First Rule of Program Optimization: Don't do it. The Second Rule of Program Optimization (for experts only!): Don't do it yet. - Michael A. Jackson",
  "Premature optimization is the mind-killer. - Samuel Tesla",
  "A fool with a tool is still a fool. - Unknown",
  "Never trust a programmer who can spell. - Anonymous",
  "Never attribute to malice that which can be adequately explained by stupidity. - Hanlon's Razor",
  "To Err is human, to Debug is Divine. - Unknown",
  "Half-knowledge is dangerous. - Famous quote that applies to everything",
  "I am not an engineer, I am a software engineer. - Unknown",
];
